name: Debug workflow dispatch

on:
  workflow_dispatch:
    inputs:
      foo:
        description: Foo?
        required: true
        type: string
      bar:
        description: Bar?
        required: false
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - if: ${{ startsWith('foo_', inputs.foo) }}
        run: echo "Yes, start with foo_ => $INPUT_FOO"
      - if: ${{ !(startsWith('foo_', inputs.foo)) }}
        run: echo "Nop, odes not start with foo_ => $INPUT_FOO"
