name: Debug workflow dispatch

on:
  workflow_dispatch:
    inputs:
      foo:
        description: Foo?
        required: true
        type: string
      bar:
        description: something else
        required: false
        type: string
        default: bar
      id:
        description: Id to find a specific workflow
        required: false
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: ${{ github.event.inputs.id }}
        run: |
          cat > /tmp/inputs <<'EOF'
            ${{ toJSON(github.event.inputs) }}
            EOF
          cat /tmp/inputs
          cat /tmp/inputs | jq

      - uses: hmarr/debug-action@v2
      - run: env
      - run: |
          echo "ab ${{ github.event.inputs.foo == 'foo' && format('...{0}...', 'ifTrue') || '' }} cd"

      - uses: actions/checkout@v2
      - run: |
          pwd
          cd foo/bar/baz
          cat hello.txt
      - run: |
          pwd
      # - run: |
      #     echo "${{ github.event.inputs.bar || 'BAZ!' }}"
      # - if: ${{ startsWith(github.event.inputs.foo, 'foo_') }}
      #   run: echo "Yes, start with foo_ => ${{ github.event.inputs.foo }}"
      # - if: ${{ !(startsWith(github.event.inputs.foo, 'foo_')) }}
      #   run: echo "Nop, does not start with foo_ => ${{ github.event.inputs.foo }}"
      # - run: |
      #     echo "$INPUT_FOO"
      #     echo "${{ env.INPUT_FOO }}"
          
      #     echo $GITHUB_ENV
      #     cat $GITHUB_ENV
          
      #     echo "INPUT_FOO=${{ github.event.inputs.foo || 'nop' }}" >> $GITHUB_ENV
          
      # - run: |
      #     echo "$INPUT_FOO"
      #     echo "${{ env.INPUT_FOO }}"

      # - uses: actions/checkout@v2
      # - run: |
      #     date > generated.txt
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add .
      #     git commit -m "generated"
      #     git push
