name: Debug workflow dispatch

on:
  workflow_dispatch:
    inputs:
      foo:
        description: Foo?
        required: true
        type: string
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - run: env
      - if: ${{ startsWith(github.event.inputs.foo, 'foo_') }}
        run: echo "Yes, start with foo_ => ${{ github.event.inputs.foo }}"
      - if: ${{ !(startsWith(github.event.inputs.foo, 'foo_')) }}
        run: echo "Nop, odes not start with foo_ => ${{ github.event.inputs.foo }}"
      - run: |
          echo "$INPUT_FOO"
          echo "${{ env.INPUT_FOO }}"
