name: Pull request automated

on:
  workflow_dispatch:
    inputs:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: hmarr/debug-action@v2

      - run: |
          date > generated.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
